# Generated by Django 4.2.15 on 2024-09-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.items'),
        ),
    ]
